export * from "./types";
export * from "./entities";
export { createCrudService } from "./createCrudService";

export { default as userService } from "./userService";
export { default as departmentService } from "./departmentService";
export { default as shiftService } from "./shiftService";
export { default as leaveTypeService } from "./leaveTypeService";
export { default as officialHolidayService } from "./officialHolidayService";
export { default as accountService } from "./accountService";
export { default as allowanceTypeService } from "./allowanceTypeService";
export { default as absenceTypeService } from "./absenceTypeService";
export { default as bonusTypeService } from "./bonusTypeService";
export { default as insuranceSettingsService } from "./insuranceSettingsService";
export { default as employeeService } from "./employeeService";
export { default as employeeDocumentService } from "./employeeDocumentService";
export { default as employeeRelativeService } from "./employeeRelativeService";
export { default as employeeExperienceService } from "./employeeExperienceService";
export { default as contractService } from "./contractService";
export { default as contractAllowanceService } from "./contractAllowanceService";
export { default as contractLeaveService } from "./contractLeaveService";
export { default as custodyService } from "./custodyService";
export { default as employeeLoanService } from "./employeeLoanService";
export { default as employeeBonusService } from "./employeeBonusService";
export { default as absenceService } from "./absenceService";
export { default as leaveRequestService } from "./leaveRequestService";
export { default as attendanceService } from "./attendanceService";
export { default as payrollRunService } from "./payrollRunService";
export { default as payrollDetailService } from "./payrollDetailService";
export { default as journalEntryService } from "./journalEntryService";
export { default as accountingPeriodService } from "./accountingPeriodService";
export { default as auditLogService } from "./auditLogService";
export { default as reportsService } from "./reportsService";

// Legacy aliases used in pages
export { default as holidayService } from "./officialHolidayService";
export { default as insuranceService } from "./insuranceSettingsService";
export { default as relativeService } from "./employeeRelativeService";
export { default as experienceService } from "./employeeExperienceService";
export { default as documentService } from "./employeeDocumentService";
export { default as loanService } from "./employeeLoanService";
export { default as bonusService } from "./employeeBonusService";
